<?php 
return array(
	/* 'manual_field' => array(
		'title' => __( 'Configuration Manual', 'woocommerce-paypal-express-mx' ),
		'type' => 'html',
		'description' => ''
	), */
	'enabled' => array(
		'title' => __( 'Enable/Disable', 'woocommerce-paypal-express-mx' ),
		'type' => 'checkbox',
		'label' => __( 'Enable Paypal Express Checkout', 'woocommerce-paypal-express-mx' ),
		'default' => 'yes'
	),
	'title' => array(
		'title'       => __( 'Title', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'description' => __( 'This controls the title which the user sees during checkout.', 'woocommerce-paypal-express-mx' ),
		'default'     => __( 'PayPal Express Checkout', 'woocommerce-paypal-express-mx' ),
		'desc_tip'    => true,
	),
	'description' => array(
		'title'       => __( 'Description', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'desc_tip'    => true,
		'description' => __( 'This controls the description which the user sees during checkout.', 'woocommerce-paypal-express-mx' ),
		'default'     => __( 'Pay via PayPal; you can pay with your credit card if you don\'t have a PayPal account.', 'woocommerce-paypal-express-mx' ),
	),
	'debug' => array(
		'title' => __( 'Debug', 'woocommerce-paypal-express-mx' ),
		'type' => 'checkbox',
		'label' => __( 'Enable log', 'woocommerce-paypal-express-mx' ),
		'default' => 'no',
		'description' => sprintf( __( 'To review the log of Paypal, see the directory: %s', 'woocommerce-paypal-express-mx' ), '<code>/wp-content/plugins/woocommerce-paypal-express-mx/logs/</code>' ),
	),
	'api_credentials' => array(
		'title'       => __( 'API Credentials', 'woocommerce-paypal-express-mx' ),
		'type'        => 'title',
		'description' => $api_creds_text,
	),
	'environment' => array(
		'title'       => __( 'Environment', 'woocommerce-paypal-express-mx' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select',
		'description' => __( 'This setting specifies whether you will process live transactions, or whether you will process simulated transactions using the PayPal Sandbox.', 'woocommerce-paypal-express-mx' ),
		'default'     => 'live',
		'desc_tip'    => true,
		'options'     => array(
			'live'    => __( 'Live', 'woocommerce-paypal-express-mx' ),
			'sandbox' => __( 'Sandbox', 'woocommerce-paypal-express-mx' ),
		),
	),
	'api_username' => array(
		'title'       => __( 'API Username', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'description' => __( 'Get your API credentials from PayPal.', 'woocommerce-paypal-express-mx' ),
		'default'     => '',
		'desc_tip'    => true,
	),
	'api_password' => array(
		'title'       => __( 'API Password', 'woocommerce-paypal-express-mx' ),
		'type'        => 'password',
		'description' => __( 'Get your API credentials from PayPal.', 'woocommerce-paypal-express-mx' ),
		'default'     => '',
		'desc_tip'    => true,
	),
	'api_signature' => array(
		'title'       => __( 'API Signature', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'description' => __( 'Get your API credentials from PayPal.', 'woocommerce-paypal-express-mx' ),
		'default'     => '',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional if you provide a certificate below', 'woocommerce-paypal-express-mx' ),
	),
	'api_certificate' => array(
		'title'       => __( 'API Certificate', 'woocommerce-paypal-express-mx' ),
		'type'        => 'file',
		'description' => $api_certificate_msg,
		'default'     => '',
	),
	'api_subject' => array(
		'title'       => __( 'API Subject', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'description' => __( 'If you\'re processing transactions on behalf of someone else\'s PayPal account, enter their email address or Secure Merchant Account ID (also known as a Payer ID) here. Generally, you must have API permissions in place with the other account in order to process anything other than "sale" transactions for them.', 'woocommerce-paypal-express-mx' ),
		'default'     => '',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
	'features' => array(
		'title'       => __( 'Features enabled', 'woocommerce-paypal-express-mx' ),
		'type'        => 'title',
	),
	'cart_checkout_enabled' => array(
		'title'       => __( 'Checkout on cart page', 'woocommerce-paypal-express-mx' ),
		'type'        => 'checkbox',
		'label'       => __( 'Enable PayPal checkout on the cart page', 'woocommerce-paypal-express-mx' ),
		'description' => __( 'This shows or hides the PayPal checkout button on the cart page.', 'woocommerce-paypal-express-mx' ),
		'desc_tip'    => true,
		'default'     => 'yes',
	),
	'product_checkout_enabled' => array(
		'title'       => __( 'Checkout on Product', 'woocommerce-paypal-express-mx' ),
		'type'        => 'checkbox',
		'label'       => __( 'Checkout on Product', 'woocommerce-paypal-express-mx' ),
		'default'     => 'no',
		'desc_tip'    => true,
		'description' => __( 'Enable Express checkout on Product view.', 'woocommerce-paypal-express-mx' ),
	),
	'invoice_prefix' => array(
		'title'       => __( 'Invoice Prefix', 'woocommerce-paypal-express-mx' ),
		'type'        => 'text',
		'description' => __( 'Please enter a prefix for your invoice numbers. If you use your PayPal account for multiple stores ensure this prefix is unique as PayPal will not allow orders with the same invoice number.', 'woocommerce-paypal-express-mx' ),
		'default'     => 'WC-',
		'desc_tip'    => true,
	),
	'require_confirmed_address' => array(
		'title'       => __( 'Require confirmed address by Paypal', 'woocommerce-paypal-express-mx' ),
		'type'        => 'checkbox',
		'label'       => __( 'Require confirmed address by Paypal', 'woocommerce-paypal-express-mx' ),
		'default'     => 'no',
		'description' => __( 'Require buyer to enter their confirmed address during checkout', 'woocommerce-paypal-express-mx' ),
	),
	/* 'require_billing_address' => array(
		'title'       => __( 'Billing Addresses', 'woocommerce-paypal-express-mx' ),
		'type'        => 'checkbox',
		'label'       => __( 'Require Billing Address', 'woocommerce-paypal-express-mx' ),
		'default'     => 'no',
		'description' => sprintf( __( 'PayPal only returns a shipping address back to the website. To make sure billing address is returned as well, please enable this functionality on your PayPal account by calling %1$sPayPal Technical Support%2$s.', 'woocommerce-paypal-express-mx' ), '<a href="https://www.paypal.com/us/selfhelp/contact/call">', '</a>' ),
	), */
	'paymentaction' => array(
		'title'       => __( 'Payment Action', 'woocommerce-paypal-express-mx' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select',
		'description' => __( 'Choose whether you wish to capture funds immediately or authorize payment only.', 'woocommerce-paypal-express-mx' ),
		'default'     => 'sale',
		'desc_tip'    => true,
		'options'     => array(
			'sale'          => __( 'Sale', 'woocommerce-paypal-express-mx' ),
			'authorization' => __( 'Authorize', 'woocommerce-paypal-express-mx' ),
		),
	),
	'allow_note_enabled' => array(
		'title'       => __( 'Allow Note on checkout', 'woocommerce-paypal-express-mx' ),
		'type'        => 'checkbox',
		'label'       => __( 'Allow Note on checkout', 'woocommerce-paypal-express-mx' ),
		'default'     => 'no',
		'description' => __( 'Customer may enter a note to the merchant on the PayPal page during checkout', 'woocommerce-paypal-express-mx' ),
	),
	'style' => array(
		'title'       => __( 'Style on Checkout', 'woocommerce-paypal-express-mx' ),
		'type'        => 'title',
	),
	'landing_page' => array(
		'title'       => __( 'Landing Page', 'woocommerce-paypal-express-mx' ),
		'type'        => 'select',
		'class'       => 'wc-enhanced-select',
		'description' => __( 'Type of PayPal page to display.', 'woocommerce-paypal-express-mx' ),
		'default'     => 'Login',
		'desc_tip'    => true,
		'options'     => array(
			'Billing' => _x( 'Billing (Non-PayPal account)', 'Type of PayPal page', 'woocommerce-paypal-express-mx' ),
			'Login'   => _x( 'Login (PayPal account login)', 'Type of PayPal page', 'woocommerce-paypal-express-mx' ),
		),
	),
	'logo_image_url' => array(
		'title'       => __( 'Logo Image (190×60)', 'woocommerce-paypal-express-mx' ),
		'type'        => 'media',
		'description' => __( 'If you want PayPal to co-brand the checkout page with your logo, enter the URL of your logo image here.<br/>The image must be no larger than 190x60, GIF, PNG, or JPG format, and should be served over HTTPS.', 'woocommerce-paypal-express-mx' ),
		'preview'     => '' !== $this->get_option('logo_image_url') ? wp_get_attachment_image( $this->get_option('logo_image_url'), 'pplogo', false, array( 'id' => 'logo_image_url-image' ) ) : '',
		'max-width'   => '190',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
	'header_image_url' => array(
		'title'       => __( 'Header Image (750×90)', 'woocommerce-paypal-express-mx' ),
		'type'        => 'media',
		'description' => __( 'If you want PayPal to co-brand the checkout page with your header, enter the URL of your header image here.<br/>The image must be no larger than 750x90, GIF, PNG, or JPG format, and should be served over HTTPS.', 'woocommerce-paypal-express-mx' ),
		'preview'     => '' !== $this->get_option('header_image_url') ? wp_get_attachment_image( $this->get_option('header_image_url'), 'ppheader', false, array( 'id' => 'header_image_url-image' ) ) : '',
		'max-width'   => '750',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
	'background_header_color' => array(
		'title'       => __( 'Background color for the header of the payment', 'woocommerce-paypal-express-mx' ),
		'type'        => 'color',
		'description' => __( 'Background color for the header of the payment', 'woocommerce-paypal-express-mx' ),
		'default'     => '#ffffff',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
	'border_header_color' => array(
		'title'       => __( 'Border color for the header of the payment', 'woocommerce-paypal-express-mx' ),
		'type'        => 'color',
		'description' => __( 'Border color for the header of the payment', 'woocommerce-paypal-express-mx' ),
		'default'     => '#000000',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
	'background_page_color' => array(
		'title'       => __( 'Background color for the payment page', 'woocommerce-paypal-express-mx' ),
		'type'        => 'color',
		'description' => __( 'Background color for the header of the payment', 'woocommerce-paypal-express-mx' ),
		'default'     => '#ffffff',
		'desc_tip'    => true,
		'placeholder' => __( 'Optional', 'woocommerce-paypal-express-mx' ),
	),
);